### ISSUE TITLE
Call to undefined method Weblee\Mandrill\Mail::message()

### ISSUE THREAD

**Issue by mcblum** [weblee/Mandrill#1]
Any idea why this would be happening? Sending via Facade with the code
\MandrillMail::message()->sendTemplate($template_name, $template_content, $message);

**Comment by ghost** [comment]
i'm sure that it should be messages() not message()

take a look at 
weblee\mandrill\src\Mail.php

**Comment by iamgoodbytes** [comment]
@mcblum see the answer by @Spycomb he's right. Using messages() is the way to go. It's probably a typo in the docs at https://github.com/weblee/Mandrill

**Comment by mcblum** [comment]
Forgot to say thanks for the answer! I hate it when people don't reply after they've been helped by the community.

**Comment by iamgoodbytes** [comment]
Glad it helped you out! Thanks to @mcblum for spotting the issue.
